export const ALL_MESSAGE = "ALL_MESSAGE";
export const NEW_MESSAGE = "NEW_MESSAGE";
export const REMOVE_ALL_MESSAGE = "REMOVE_ALL_MESSAGE";

export const ALL_PROBLEM = "ALL_PROBLEM";
export const NEW_PROBLEM = "NEW_PROBLEM";
export const UPDATED_PROBLEM = "UPDATED_PROBLEM";
export const REMOVED_PROBLEM = "REMOVED_PROBLEM";

export const ALL_SOLUTION = "ALL_SOLUTION";
export const NEW_SOLUTION = "NEW_SOLUTION";
export const UPDATED_SOLUTION = "UPDATED_SOLUTION";
export const REMOVE_ALL_SOLUTION = "REMOVE_ALL_SOLUTION";

export const NEW_MESSAGE_NOTIFY = "NEW_MESSAGE_NOTIFY";
export const SEEN_MESSAGE_NOTIFY = "SEEN_MESSAGE_NOTIFY";

export const NEW_SOLUTION_NOTIFY = "NEW_SOLUTION_NOTIFY";
export const SEEN_SOLUTION_NOTIFY = "SEEN_SOLUTION_NOTIFY";

export const NEW_PROBLEM_NOTIFY = "NEW_PROBLEM_NOTIFY";
export const SEEN_PROBLEM_NOTIFY = "SEEN_PROBLEM_NOTIFY";

export const ROOM_INFO = "ROOM_INFO";
export const NEW_ROOM_INFO = "NEW_ROOM_INFO";

export const USER_INFO = "USER_INFO";
